name: Run Taiko ETH Deposit and Withdraw Script

on:
  workflow_dispatch:         # Manual trigger
  schedule:
    - cron: '2 2 * * *'     # (02:40 UTC)

jobs:
  run_transaction_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install required Python packages
      run: |
        python -m pip install --upgrade pip
        pip install web3 python-dotenv

    - name: Create .env file from GitHub secrets
      run: |
        echo "PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" >> .env
        echo "TAIKO_RPC_URL=${{ secrets.TAIKO_RPC_URL }}" >> .env
        echo "CONTRACT_ADDRESS=${{ secrets.CONTRACT_ADDRESS }}" >> .env
        echo "LENDING_POOL=${{ secrets.LENDING_POOL }}" >> .env

    - name: Run the Taiko transaction script
      run: python taiko_tx.py
